//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menafrinet.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Menafrinet.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Create a Data Package.
        /// </summary>
        public static string _1_Create_a_Data_Package {
            get {
                return ResourceManager.GetString("_1_Create_a_Data_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Open import folder.
        /// </summary>
        public static string _1_Open_import_folder {
            get {
                return ResourceManager.GetString("_1_Open_import_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Import.
        /// </summary>
        public static string _2_Import {
            get {
                return ResourceManager.GetString("_2_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Language Settings.
        /// </summary>
        public static string _Language_Settings {
            get {
                return ResourceManager.GetString("_Language_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Language Settings.
        /// </summary>
        public static string _Language_Settings0 {
            get {
                return ResourceManager.GetString("_Language_Settings0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string _m_Lang_Language_Settings {
            get {
                return ResourceManager.GetString("_m_Lang_Language_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string _m_Lang_User_Settings {
            get {
                return ResourceManager.GetString("_m_Lang_User_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Site Settings.
        /// </summary>
        public static string _Site_Settings {
            get {
                return ResourceManager.GetString("_Site_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            User Settings.
        /// </summary>
        public static string _User_Settings {
            get {
                return ResourceManager.GetString("_User_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           User Settings.
        /// </summary>
        public static string _User_Settings0 {
            get {
                return ResourceManager.GetString("_User_Settings0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Residents, Consultants and Field Sites.
        /// </summary>
        public static string Add_Residents_Consultants_and_ {
            get {
                return ResourceManager.GetString("Add_Residents_Consultants_and_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merge.
        /// </summary>
        public static string ButtonMerge {
            get {
                return ResourceManager.GetString("ButtonMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort.
        /// </summary>
        public static string Cohort {
            get {
                return ResourceManager.GetString("Cohort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort End Date.
        /// </summary>
        public static string Cohort_End_Date {
            get {
                return ResourceManager.GetString("Cohort_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort Start Date.
        /// </summary>
        public static string Cohort_Start_Date {
            get {
                return ResourceManager.GetString("Cohort_Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string ColHeaderAge {
            get {
                return ResourceManager.GetString("ColHeaderAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string ColHeaderClassification {
            get {
                return ResourceManager.GetString("ColHeaderClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        public static string ColHeaderCreatedOn {
            get {
                return ResourceManager.GetString("ColHeaderCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPID.
        /// </summary>
        public static string ColHeaderEPID {
            get {
                return ResourceManager.GetString("ColHeaderEPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Week.
        /// </summary>
        public static string ColHeaderEpiWeek {
            get {
                return ResourceManager.GetString("ColHeaderEpiWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Lab Result.
        /// </summary>
        public static string ColHeaderFinalLabResult {
            get {
                return ResourceManager.GetString("ColHeaderFinalLabResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ColHeaderFirstName {
            get {
                return ResourceManager.GetString("ColHeaderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Facility.
        /// </summary>
        public static string ColHeaderHealthFacility {
            get {
                return ResourceManager.GetString("ColHeaderHealthFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ColHeaderLastName {
            get {
                return ResourceManager.GetString("ColHeaderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LP Performed.
        /// </summary>
        public static string ColHeaderLPPerformed {
            get {
                return ResourceManager.GetString("ColHeaderLPPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string ColHeaderOutcome {
            get {
                return ResourceManager.GetString("ColHeaderOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting District.
        /// </summary>
        public static string ColHeaderReportingDistrict {
            get {
                return ResourceManager.GetString("ColHeaderReportingDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string ColHeaderSex {
            get {
                return ResourceManager.GetString("ColHeaderSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColHeaderStatus {
            get {
                return ResourceManager.GetString("ColHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on.
        /// </summary>
        public static string ColHeaderUpdatedOn {
            get {
                return ResourceManager.GetString("ColHeaderUpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ColHeaderYear {
            get {
                return ResourceManager.GetString("ColHeaderYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the last import.
        /// </summary>
        public static string Date_of_the_last_import {
            get {
                return ResourceManager.GetString("Date_of_the_last_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-Identify.
        /// </summary>
        public static string De_Identify {
            get {
                return ResourceManager.GetString("De_Identify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create data packet.
        /// </summary>
        public static string ExportCreateDataPackage {
            get {
                return ResourceManager.GetString("ExportCreateDataPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export destination site:.
        /// </summary>
        public static string ExportDestinationSite {
            get {
                return ResourceManager.GetString("ExportDestinationSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export destination type:.
        /// </summary>
        public static string ExportDestinationType {
            get {
                return ResourceManager.GetString("ExportDestinationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        public static string ExportEndDate {
            get {
                return ResourceManager.GetString("ExportEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last export:.
        /// </summary>
        public static string ExportLastExportDate {
            get {
                return ResourceManager.GetString("ExportLastExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID of last export:.
        /// </summary>
        public static string ExportLastExportUserID {
            get {
                return ResourceManager.GetString("ExportLastExportUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open transmisison folder.
        /// </summary>
        public static string ExportOpenTransmissionFolder {
            get {
                return ResourceManager.GetString("ExportOpenTransmissionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purge old transmission files.
        /// </summary>
        public static string ExportPurgeFiles {
            get {
                return ResourceManager.GetString("ExportPurgeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records exported:.
        /// </summary>
        public static string ExportRecordsExported {
            get {
                return ResourceManager.GetString("ExportRecordsExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string ExportStartDate {
            get {
                return ResourceManager.GetString("ExportStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export status:.
        /// </summary>
        public static string ExportStatus {
            get {
                return ResourceManager.GetString("ExportStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export type:.
        /// </summary>
        public static string ExportType {
            get {
                return ResourceManager.GetString("ExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all.
        /// </summary>
        public static string ExportTypeAll {
            get {
                return ResourceManager.GetString("ExportTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all since last.
        /// </summary>
        public static string ExportTypeAllSinceLast {
            get {
                return ResourceManager.GetString("ExportTypeAllSinceLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string ExportTypeDates {
            get {
                return ResourceManager.GetString("ExportTypeDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ExportTypeMonth {
            get {
                return ResourceManager.GetString("ExportTypeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files packaged:.
        /// </summary>
        public static string Files_packaged {
            get {
                return ResourceManager.GetString("Files_packaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import status.
        /// </summary>
        public static string Import_status {
            get {
                return ResourceManager.GetString("Import_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Export Date: .
        /// </summary>
        public static string Last_Export_Date {
            get {
                return ResourceManager.GetString("Last_Export_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last merge:.
        /// </summary>
        public static string LastMergeDate {
            get {
                return ResourceManager.GetString("LastMergeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID of last merge:.
        /// </summary>
        public static string LastMergeUserID {
            get {
                return ResourceManager.GetString("LastMergeUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Management System of Case-by-Case Surveillance Database.
        /// </summary>
        public static string MainHeading {
            get {
                return ResourceManager.GetString("MainHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge status:.
        /// </summary>
        public static string MergeStatus {
            get {
                return ResourceManager.GetString("MergeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       New Record.
        /// </summary>
        public static string NewRecord {
            get {
                return ResourceManager.GetString("NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ohort.
        /// </summary>
        public static string ohort {
            get {
                return ResourceManager.GetString("ohort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open merge folder.
        /// </summary>
        public static string OpenMergeFolder {
            get {
                return ResourceManager.GetString("OpenMergeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format: Report viewer or Epi Info.
        /// </summary>
        public static string Output_format_Report_viewer_or {
            get {
                return ResourceManager.GetString("Output_format_Report_viewer_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package files merged:.
        /// </summary>
        public static string PackagesMerged {
            get {
                return ResourceManager.GetString("PackagesMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous import date.
        /// </summary>
        public static string Previous_import_date {
            get {
                return ResourceManager.GetString("Previous_import_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records merged:.
        /// </summary>
        public static string RecordsMerged {
            get {
                return ResourceManager.GetString("RecordsMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Format.
        /// </summary>
        public static string Report_Format {
            get {
                return ResourceManager.GetString("Report_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has been updated and needs review..
        /// </summary>
        public static string res {
            get {
                return ResourceManager.GetString("res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project has a similar Project Classification and aproximate Date assigned..
        /// </summary>
        public static string res0 {
            get {
                return ResourceManager.GetString("res0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Date.
        /// </summary>
        public static string res1 {
            get {
                return ResourceManager.GetString("res1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Email.
        /// </summary>
        public static string res10 {
            get {
                return ResourceManager.GetString("res10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed.
        /// </summary>
        public static string res11 {
            get {
                return ResourceManager.GetString("res11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string res12 {
            get {
                return ResourceManager.GetString("res12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string res13 {
            get {
                return ResourceManager.GetString("res13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string res14 {
            get {
                return ResourceManager.GetString("res14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Classification:.
        /// </summary>
        public static string res15 {
            get {
                return ResourceManager.GetString("res15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspected Disease.
        /// </summary>
        public static string res16 {
            get {
                return ResourceManager.GetString("res16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial ICD10 Name:.
        /// </summary>
        public static string res17 {
            get {
                return ResourceManager.GetString("res17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Category:   .
        /// </summary>
        public static string res18 {
            get {
                return ResourceManager.GetString("res18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Entered By:.
        /// </summary>
        public static string res19 {
            get {
                return ResourceManager.GetString("res19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        public static string res2 {
            get {
                return ResourceManager.GetString("res2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDPeTT User Guide.
        /// </summary>
        public static string res20 {
            get {
                return ResourceManager.GetString("res20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string res21 {
            get {
                return ResourceManager.GetString("res21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort Number.
        /// </summary>
        public static string res22 {
            get {
                return ResourceManager.GetString("res22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University/Training Institution.
        /// </summary>
        public static string res23 {
            get {
                return ResourceManager.GetString("res23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Status.
        /// </summary>
        public static string res24 {
            get {
                return ResourceManager.GetString("res24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FETP Track.
        /// </summary>
        public static string res25 {
            get {
                return ResourceManager.GetString("res25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee Email.
        /// </summary>
        public static string res26 {
            get {
                return ResourceManager.GetString("res26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string res27 {
            get {
                return ResourceManager.GetString("res27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string res28 {
            get {
                return ResourceManager.GetString("res28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Create a data packet.
        /// </summary>
        public static string res29 {
            get {
                return ResourceManager.GetString("res29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string res3 {
            get {
                return ResourceManager.GetString("res3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last export date.
        /// </summary>
        public static string res30 {
            get {
                return ResourceManager.GetString("res30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deidentify.
        /// </summary>
        public static string res31 {
            get {
                return ResourceManager.GetString("res31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Residents and Consultants.
        /// </summary>
        public static string res32 {
            get {
                return ResourceManager.GetString("res32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        public static string res33 {
            get {
                return ResourceManager.GetString("res33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Date.
        /// </summary>
        public static string res34 {
            get {
                return ResourceManager.GetString("res34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the export.
        /// </summary>
        public static string res35 {
            get {
                return ResourceManager.GetString("res35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string res36 {
            get {
                return ResourceManager.GetString("res36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enter Field Site.
        /// </summary>
        public static string res37 {
            get {
                return ResourceManager.GetString("res37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _User Settings.
        /// </summary>
        public static string res38 {
            get {
                return ResourceManager.GetString("res38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string res39 {
            get {
                return ResourceManager.GetString("res39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string res4 {
            get {
                return ResourceManager.GetString("res4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string res40 {
            get {
                return ResourceManager.GetString("res40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residents.
        /// </summary>
        public static string res41 {
            get {
                return ResourceManager.GetString("res41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants.
        /// </summary>
        public static string res42 {
            get {
                return ResourceManager.GetString("res42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string res43 {
            get {
                return ResourceManager.GetString("res43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string res5 {
            get {
                return ResourceManager.GetString("res5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Affiliation.
        /// </summary>
        public static string res6 {
            get {
                return ResourceManager.GetString("res6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor.
        /// </summary>
        public static string res7 {
            get {
                return ResourceManager.GetString("res7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string res8 {
            get {
                return ResourceManager.GetString("res8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string res9 {
            get {
                return ResourceManager.GetString("res9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident.
        /// </summary>
        public static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        public static string Select_Item {
            get {
                return ResourceManager.GetString("Select_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Merge Status.
        /// </summary>
        public static string SiteMergeStatus {
            get {
                return ResourceManager.GetString("SiteMergeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the Export.
        /// </summary>
        public static string Status_of_the_Export {
            get {
                return ResourceManager.GetString("Status_of_the_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the merge.
        /// </summary>
        public static string Status_of_the_merge {
            get {
                return ResourceManager.GetString("Status_of_the_merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type:.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort.
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data packages in the import folder..
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline.
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident Name:.
        /// </summary>
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full: Add Residents, Consultants and Field Sites.
        /// </summary>
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Format.
        /// </summary>
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format: Report viewer or Epi Info.
        /// </summary>
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDPeTT User Videos.
        /// </summary>
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD10 Code:.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University/Institution:.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting:.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residentes.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultoras.
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident Name:.
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string TabAnalysis {
            get {
                return ResourceManager.GetString("TabAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        public static string TabDataEntry {
            get {
                return ResourceManager.GetString("TabDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string TabMerge {
            get {
                return ResourceManager.GetString("TabMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Merging.
        /// </summary>
        public static string TabMergeHeader {
            get {
                return ResourceManager.GetString("TabMergeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string TabTransmission {
            get {
                return ResourceManager.GetString("TabTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string TabTransmissionHeader {
            get {
                return ResourceManager.GetString("TabTransmissionHeader", resourceCulture);
            }
        }
    }
}
