#pragma checksum "..\..\NewOutbreak.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "758733BAF6F6B56DCD0838105BA24C15"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ContactTracing.Controls;
using ContactTracing.WPF.Properties;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ContactTracing.Controls {
    
    
    /// <summary>
    /// NewOutbreak
    /// </summary>
    public partial class NewOutbreak : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel panelBackground;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock tblockFileName;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtFileName;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DockPanel spacerFileName;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtOutbreakName;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpOutbreakDate;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPrefix;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtSep;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbPattern;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbVirus;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbCountry;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnOK;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\NewOutbreak.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnCancel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ContactTracing.WPF;component/newoutbreak.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\NewOutbreak.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.panelBackground = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 2:
            this.tblockFileName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.txtFileName = ((System.Windows.Controls.TextBox)(target));
            
            #line 22 "..\..\NewOutbreak.xaml"
            this.txtFileName.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.txtFileName_PreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 4:
            this.spacerFileName = ((System.Windows.Controls.DockPanel)(target));
            return;
            case 5:
            this.txtOutbreakName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.dpOutbreakDate = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 7:
            this.txtPrefix = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.txtSep = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.cmbPattern = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.cmbVirus = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.cmbCountry = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.btnOK = ((System.Windows.Controls.Button)(target));
            
            #line 82 "..\..\NewOutbreak.xaml"
            this.btnOK.Click += new System.Windows.RoutedEventHandler(this.btnOK_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btnCancel = ((System.Windows.Controls.Button)(target));
            
            #line 83 "..\..\NewOutbreak.xaml"
            this.btnCancel.Click += new System.Windows.RoutedEventHandler(this.btnCancel_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

