//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menafrinet.View.ml_resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MultiLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MultiLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Menafrinet.View.MultiLang", typeof(MultiLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merge.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee Email.
        /// </summary>
        public static string _100 {
            get {
                return ResourceManager.GetString("_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Create a data packet.
        /// </summary>
        public static string _101 {
            get {
                return ResourceManager.GetString("_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last export date.
        /// </summary>
        public static string _102 {
            get {
                return ResourceManager.GetString("_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deidentify.
        /// </summary>
        public static string _103 {
            get {
                return ResourceManager.GetString("_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Residents and Consultants.
        /// </summary>
        public static string _104 {
            get {
                return ResourceManager.GetString("_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        public static string _105 {
            get {
                return ResourceManager.GetString("_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Date.
        /// </summary>
        public static string _106 {
            get {
                return ResourceManager.GetString("_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the export.
        /// </summary>
        public static string _107 {
            get {
                return ResourceManager.GetString("_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type:.
        /// </summary>
        public static string _108 {
            get {
                return ResourceManager.GetString("_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort.
        /// </summary>
        public static string _109 {
            get {
                return ResourceManager.GetString("_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LP Performed.
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICD10 Code:.
        /// </summary>
        public static string _110 {
            get {
                return ResourceManager.GetString("_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University/Institution:.
        /// </summary>
        public static string _111 {
            get {
                return ResourceManager.GetString("_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting:.
        /// </summary>
        public static string _112 {
            get {
                return ResourceManager.GetString("_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string _113 {
            get {
                return ResourceManager.GetString("_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residentes.
        /// </summary>
        public static string _114 {
            get {
                return ResourceManager.GetString("_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultoras.
        /// </summary>
        public static string _115 {
            get {
                return ResourceManager.GetString("_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string _116 {
            get {
                return ResourceManager.GetString("_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident Name:.
        /// </summary>
        public static string _117 {
            get {
                return ResourceManager.GetString("_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not merge data if user settings are not properly configured..
        /// </summary>
        public static string _118 {
            get {
                return ResourceManager.GetString("_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data packages in the import folder..
        /// </summary>
        public static string _119 {
            get {
                return ResourceManager.GetString("_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} was not included in the merge because of incorrect file names or validation errors..
        /// </summary>
        public static string _120 {
            get {
                return ResourceManager.GetString("_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy and paste the data package or multiple packages in this window that you want to import..
        /// </summary>
        public static string _121 {
            get {
                return ResourceManager.GetString("_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening - decrypting package....
        /// </summary>
        public static string _122 {
            get {
                return ResourceManager.GetString("_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging data for: .
        /// </summary>
        public static string _123 {
            get {
                return ResourceManager.GetString("_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects A D D E D....
        /// </summary>
        public static string _124 {
            get {
                return ResourceManager.GetString("_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants A D D E D....
        /// </summary>
        public static string _125 {
            get {
                return ResourceManager.GetString("_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainees A D D E D....
        /// </summary>
        public static string _126 {
            get {
                return ResourceManager.GetString("_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraineesFilter.
        /// </summary>
        public static string _127 {
            get {
                return ResourceManager.GetString("_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects filtered for .
        /// </summary>
        public static string _128 {
            get {
                return ResourceManager.GetString("_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successfully completed..
        /// </summary>
        public static string _129 {
            get {
                return ResourceManager.GetString("_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting District.
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export processing....
        /// </summary>
        public static string _130 {
            get {
                return ResourceManager.GetString("_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting consultants....
        /// </summary>
        public static string _131 {
            get {
                return ResourceManager.GetString("_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants de-identified.
        /// </summary>
        public static string _132 {
            get {
                return ResourceManager.GetString("_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting projects....
        /// </summary>
        public static string _133 {
            get {
                return ResourceManager.GetString("_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting residents....
        /// </summary>
        public static string _134 {
            get {
                return ResourceManager.GetString("_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects de-identified.
        /// </summary>
        public static string _135 {
            get {
                return ResourceManager.GetString("_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export sucessfully completed..
        /// </summary>
        public static string _136 {
            get {
                return ResourceManager.GetString("_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred exporting:.
        /// </summary>
        public static string _137 {
            get {
                return ResourceManager.GetString("_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee Information DeIdentified....
        /// </summary>
        public static string _138 {
            get {
                return ResourceManager.GetString("_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residents de-identified.
        /// </summary>
        public static string _139 {
            get {
                return ResourceManager.GetString("_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the ReDPeTT file from the Exports folder..
        /// </summary>
        public static string _140 {
            get {
                return ResourceManager.GetString("_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string _141 {
            get {
                return ResourceManager.GetString("_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string _142 {
            get {
                return ResourceManager.GetString("_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string _143 {
            get {
                return ResourceManager.GetString("_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects A D D E D....
        /// </summary>
        public static string _144 {
            get {
                return ResourceManager.GetString("_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving: .
        /// </summary>
        public static string _145 {
            get {
                return ResourceManager.GetString("_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Date Assigned&lt;/th&gt;.
        /// </summary>
        public static string _146 {
            get {
                return ResourceManager.GetString("_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Lead Resident&lt;/th&gt;.
        /// </summary>
        public static string _147 {
            get {
                return ResourceManager.GetString("_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 80px;&quot;&gt;Lead Cohort&lt;/th&gt;.
        /// </summary>
        public static string _148 {
            get {
                return ResourceManager.GetString("_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 90px;&quot;&gt;Mentor Full Name&lt;/th&gt;.
        /// </summary>
        public static string _149 {
            get {
                return ResourceManager.GetString("_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 90px;&quot;&gt;Supervisor Full Name&lt;/th&gt;.
        /// </summary>
        public static string _150 {
            get {
                return ResourceManager.GetString("_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 60px;&quot;&gt;Created&lt;/th&gt;.
        /// </summary>
        public static string _151 {
            get {
                return ResourceManager.GetString("_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 100px;&quot;&gt;Updated&lt;/th&gt;.
        /// </summary>
        public static string _152 {
            get {
                return ResourceManager.GetString("_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 180px;&quot;&gt;Project Title&lt;/th&gt;.
        /// </summary>
        public static string _153 {
            get {
                return ResourceManager.GetString("_153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr style=&quot;border-top: 0px solid black;&quot;&gt;.
        /// </summary>
        public static string _154 {
            get {
                return ResourceManager.GetString("_154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold;&quot;&gt;Date printed: .
        /// </summary>
        public static string _155 {
            get {
                return ResourceManager.GetString("_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold; text-decoration: underline;&quot;&gt;Project Line List&lt;/p&gt;.
        /// </summary>
        public static string _156 {
            get {
                return ResourceManager.GetString("_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold; clear: left; text-decoration: underline;&quot;&gt;Resident Driven Project Tracking Tool (ReDPeTT)&lt;/p&gt;.
        /// </summary>
        public static string _157 {
            get {
                return ResourceManager.GetString("_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 180px;&quot;&gt;Full Name&lt;/th&gt;.
        /// </summary>
        public static string _158 {
            get {
                return ResourceManager.GetString("_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 180px;&quot;&gt;Cohort Number&lt;/th&gt;.
        /// </summary>
        public static string _159 {
            get {
                return ResourceManager.GetString("_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated on.
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;University/Training Institution&lt;/th&gt;.
        /// </summary>
        public static string _160 {
            get {
                return ResourceManager.GetString("_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Graduation Status&lt;/th&gt;.
        /// </summary>
        public static string _161 {
            get {
                return ResourceManager.GetString("_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;FETP Track&lt;/th&gt;.
        /// </summary>
        public static string _162 {
            get {
                return ResourceManager.GetString("_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 30px;&quot;&gt;Mobile Phone&lt;/th&gt;.
        /// </summary>
        public static string _163 {
            get {
                return ResourceManager.GetString("_163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 30px;&quot;&gt;Trainee Email&lt;/th&gt;.
        /// </summary>
        public static string _164 {
            get {
                return ResourceManager.GetString("_164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/tr&gt;.
        /// </summary>
        public static string _165 {
            get {
                return ResourceManager.GetString("_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 100px;&quot;&gt;Created&lt;/th&gt;.
        /// </summary>
        public static string _166 {
            get {
                return ResourceManager.GetString("_166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold; text-decoration: underline;&quot;&gt;Resident Line List&lt;/p&gt;.
        /// </summary>
        public static string _167 {
            get {
                return ResourceManager.GetString("_167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold;&quot;&gt;Filter: .
        /// </summary>
        public static string _168 {
            get {
                return ResourceManager.GetString("_168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 100px;&quot;&gt;Consultant Email&lt;/th&gt;.
        /// </summary>
        public static string _169 {
            get {
                return ResourceManager.GetString("_169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 30px;&quot;&gt;Supervisor&lt;/th&gt;.
        /// </summary>
        public static string _170 {
            get {
                return ResourceManager.GetString("_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Mentor&lt;/th&gt;.
        /// </summary>
        public static string _171 {
            get {
                return ResourceManager.GetString("_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Professional Affiliation&lt;/th&gt;.
        /// </summary>
        public static string _172 {
            get {
                return ResourceManager.GetString("_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 180px;&quot;&gt;Full Name&lt;/th&gt;.
        /// </summary>
        public static string _173 {
            get {
                return ResourceManager.GetString("_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 100px;&quot;&gt;Created&lt;/th&gt;.
        /// </summary>
        public static string _174 {
            get {
                return ResourceManager.GetString("_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold;&quot;&gt;Filter: .
        /// </summary>
        public static string _175 {
            get {
                return ResourceManager.GetString("_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold; text-decoration: underline;&quot;&gt;Consultant Line List&lt;/p&gt;.
        /// </summary>
        public static string _176 {
            get {
                return ResourceManager.GetString("_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: &lt;b&gt;.
        /// </summary>
        public static string _177 {
            get {
                return ResourceManager.GetString("_177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 60px;&quot;&gt;Updated&lt;/th&gt;.
        /// </summary>
        public static string _178 {
            get {
                return ResourceManager.GetString("_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging data for: .
        /// </summary>
        public static string _179 {
            get {
                return ResourceManager.GetString("_179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create data packet.
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants A D D E D....
        /// </summary>
        public static string _180 {
            get {
                return ResourceManager.GetString("_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residents A D D E D....
        /// </summary>
        public static string _181 {
            get {
                return ResourceManager.GetString("_181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving: .
        /// </summary>
        public static string _182 {
            get {
                return ResourceManager.GetString("_182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 90px;&quot;&gt;Project Status&lt;/th&gt;.
        /// </summary>
        public static string _183 {
            get {
                return ResourceManager.GetString("_183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export destination site:.
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 90px;&quot;&gt;Project Status&lt;/th&gt;.
        /// </summary>
        public static string _191 {
            get {
                return ResourceManager.GetString("_191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Sites A D D E D....
        /// </summary>
        public static string _192 {
            get {
                return ResourceManager.GetString("_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Field Sites....
        /// </summary>
        public static string _193 {
            get {
                return ResourceManager.GetString("_193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the Export.
        /// </summary>
        public static string _194 {
            get {
                return ResourceManager.GetString("_194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Residents, Consultants and Field Sites.
        /// </summary>
        public static string _195 {
            get {
                return ResourceManager.GetString("_195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Export Date: .
        /// </summary>
        public static string _196 {
            get {
                return ResourceManager.GetString("_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-Identify.
        /// </summary>
        public static string _197 {
            get {
                return ResourceManager.GetString("_197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Create a Data Package.
        /// </summary>
        public static string _198 {
            get {
                return ResourceManager.GetString("_198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residents A D D E D....
        /// </summary>
        public static string _199 {
            get {
                return ResourceManager.GetString("_199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export destination type:.
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline Information DeIdentified....
        /// </summary>
        public static string _200 {
            get {
                return ResourceManager.GetString("_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             Site Settings.
        /// </summary>
        public static string _201 {
            get {
                return ResourceManager.GetString("_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            User Settings.
        /// </summary>
        public static string _202 {
            get {
                return ResourceManager.GetString("_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Language Settings.
        /// </summary>
        public static string _203 {
            get {
                return ResourceManager.GetString("_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline A D D E D....
        /// </summary>
        public static string _204 {
            get {
                return ResourceManager.GetString("_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    &lt;p style=&quot;font-size: 13pt; font-weight: bold; text-decoration: underline;&quot;&gt;Frontline Line List&lt;/p&gt;.
        /// </summary>
        public static string _205 {
            get {
                return ResourceManager.GetString("_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontline.
        /// </summary>
        public static string _206 {
            get {
                return ResourceManager.GetString("_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Frontline data....
        /// </summary>
        public static string _207 {
            get {
                return ResourceManager.GetString("_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string _208 {
            get {
                return ResourceManager.GetString("_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app settings have been changed. The user setting changes will take full effect the next time you start the program. Please close the application and restart..
        /// </summary>
        public static string _209 {
            get {
                return ResourceManager.GetString("_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDPeTT Alert: .
        /// </summary>
        public static string _210 {
            get {
                return ResourceManager.GetString("_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project was not installed in the correctly. Please ensure the application is installed correctly..
        /// </summary>
        public static string _211 {
            get {
                return ResourceManager.GetString("_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;  Institution: &lt;b&gt;.
        /// </summary>
        public static string _212 {
            get {
                return ResourceManager.GetString("_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string _213 {
            get {
                return ResourceManager.GetString("_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;   &lt;b&gt;.
        /// </summary>
        public static string _214 {
            get {
                return ResourceManager.GetString("_214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/b&gt;.
        /// </summary>
        public static string _215 {
            get {
                return ResourceManager.GetString("_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;  Cohort number: &lt;b&gt;.
        /// </summary>
        public static string _216 {
            get {
                return ResourceManager.GetString("_216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;  Resident: &lt;b&gt;.
        /// </summary>
        public static string _217 {
            get {
                return ResourceManager.GetString("_217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;  Ending Reporting Date:  &lt;b&gt;.
        /// </summary>
        public static string _218 {
            get {
                return ResourceManager.GetString("_218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;   Beginning Reporting Date:  &lt;b&gt;.
        /// </summary>
        public static string _219 {
            get {
                return ResourceManager.GetString("_219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last export:.
        /// </summary>
        public static string _22 {
            get {
                return ResourceManager.GetString("_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Deidentified).
        /// </summary>
        public static string _220 {
            get {
                return ResourceManager.GetString("_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (FULL).
        /// </summary>
        public static string _221 {
            get {
                return ResourceManager.GetString("_221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting project data....
        /// </summary>
        public static string _222 {
            get {
                return ResourceManager.GetString("_222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Format.
        /// </summary>
        public static string _223 {
            get {
                return ResourceManager.GetString("_223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format: Report viewer or Epi Info.
        /// </summary>
        public static string _224 {
            get {
                return ResourceManager.GetString("_224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string _225 {
            get {
                return ResourceManager.GetString("_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ohort.
        /// </summary>
        public static string _226 {
            get {
                return ResourceManager.GetString("_226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 180px;&quot;&gt;Cohort Start Date&lt;/th&gt;.
        /// </summary>
        public static string _227 {
            get {
                return ResourceManager.GetString("_227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Cohort End Date&lt;/th&gt;.
        /// </summary>
        public static string _228 {
            get {
                return ResourceManager.GetString("_228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Full Name&lt;/th&gt;.
        /// </summary>
        public static string _229 {
            get {
                return ResourceManager.GetString("_229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID of last export:.
        /// </summary>
        public static string _23 {
            get {
                return ResourceManager.GetString("_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th style=&quot;width: 140px;&quot;&gt;Email&lt;/th&gt;.
        /// </summary>
        public static string _230 {
            get {
                return ResourceManager.GetString("_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project was not installed in the correctly. Please ensure the application is installed correctly.
        /// </summary>
        public static string _231 {
            get {
                return ResourceManager.GetString("_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string _232 {
            get {
                return ResourceManager.GetString("_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Settings.
        /// </summary>
        public static string _233 {
            get {
                return ResourceManager.GetString("_233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           User Settings.
        /// </summary>
        public static string _234 {
            get {
                return ResourceManager.GetString("_234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          Language Settings.
        /// </summary>
        public static string _235 {
            get {
                return ResourceManager.GetString("_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort Start Date.
        /// </summary>
        public static string _236 {
            get {
                return ResourceManager.GetString("_236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort End Date.
        /// </summary>
        public static string _237 {
            get {
                return ResourceManager.GetString("_237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string _238 {
            get {
                return ResourceManager.GetString("_238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full: Add Residents, Consultants and Field Sites.
        /// </summary>
        public static string _239 {
            get {
                return ResourceManager.GetString("_239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open transmisison folder.
        /// </summary>
        public static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string _240 {
            get {
                return ResourceManager.GetString("_240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full: Add Residents, Consultants and Field Sites.
        /// </summary>
        public static string _241 {
            get {
                return ResourceManager.GetString("_241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        public static string _242 {
            get {
                return ResourceManager.GetString("_242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDPeTT User Videos.
        /// </summary>
        public static string _243 {
            get {
                return ResourceManager.GetString("_243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full: Add Residents, Consultants and Field Sites.
        /// </summary>
        public static string _244 {
            get {
                return ResourceManager.GetString("_244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Properties.Resources.
        /// </summary>
        public static string _245 {
            get {
                return ResourceManager.GetString("_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects\TrackingMaster\ImportExport\Attachments\.
        /// </summary>
        public static string _246 {
            get {
                return ResourceManager.GetString("_246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE LanguageSettings96LanguageTranslation INNER JOIN metaFields ON LanguageSettings96LanguageTranslation.FieldName = metaFields.Name SET metaFields.PromptText = [LanguageSettings96LanguageTranslation].[TypeLabel.
        /// </summary>
        public static string _247 {
            get {
                return ResourceManager.GetString("_247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Information DeIdentified....
        /// </summary>
        public static string _248 {
            get {
                return ResourceManager.GetString("_248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purge old transmission files.
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records exported:.
        /// </summary>
        public static string _26 {
            get {
                return ResourceManager.GetString("_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        public static string _27 {
            get {
                return ResourceManager.GetString("_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export status:.
        /// </summary>
        public static string _28 {
            get {
                return ResourceManager.GetString("_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export type:.
        /// </summary>
        public static string _29 {
            get {
                return ResourceManager.GetString("_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all.
        /// </summary>
        public static string _30 {
            get {
                return ResourceManager.GetString("_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all since last.
        /// </summary>
        public static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string _33 {
            get {
                return ResourceManager.GetString("_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last merge:.
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID of last merge:.
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Management System of Case-by-Case Surveillance Database.
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge status:.
        /// </summary>
        public static string _37 {
            get {
                return ResourceManager.GetString("_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       New Record.
        /// </summary>
        public static string _38 {
            get {
                return ResourceManager.GetString("_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open merge folder.
        /// </summary>
        public static string _39 {
            get {
                return ResourceManager.GetString("_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package files merged:.
        /// </summary>
        public static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string _41 {
            get {
                return ResourceManager.GetString("_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string _42 {
            get {
                return ResourceManager.GetString("_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records merged:.
        /// </summary>
        public static string _43 {
            get {
                return ResourceManager.GetString("_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Merge Status.
        /// </summary>
        public static string _44 {
            get {
                return ResourceManager.GetString("_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string _45 {
            get {
                return ResourceManager.GetString("_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entry.
        /// </summary>
        public static string _46 {
            get {
                return ResourceManager.GetString("_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string _47 {
            get {
                return ResourceManager.GetString("_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string _48 {
            get {
                return ResourceManager.GetString("_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Merging.
        /// </summary>
        public static string _49 {
            get {
                return ResourceManager.GetString("_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPID.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission.
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Transmission.
        /// </summary>
        public static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string _52 {
            get {
                return ResourceManager.GetString("_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string _53 {
            get {
                return ResourceManager.GetString("_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string _54 {
            get {
                return ResourceManager.GetString("_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residents.
        /// </summary>
        public static string _55 {
            get {
                return ResourceManager.GetString("_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants.
        /// </summary>
        public static string _56 {
            get {
                return ResourceManager.GetString("_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string _57 {
            get {
                return ResourceManager.GetString("_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string _58 {
            get {
                return ResourceManager.GetString("_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string _59 {
            get {
                return ResourceManager.GetString("_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Week.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enter Field Site.
        /// </summary>
        public static string _60 {
            get {
                return ResourceManager.GetString("_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _User Settings.
        /// </summary>
        public static string _61 {
            get {
                return ResourceManager.GetString("_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has been updated and needs review..
        /// </summary>
        public static string _62 {
            get {
                return ResourceManager.GetString("_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project has a similar Project Classification and aproximate Date assigned..
        /// </summary>
        public static string _63 {
            get {
                return ResourceManager.GetString("_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Date.
        /// </summary>
        public static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Date.
        /// </summary>
        public static string _65 {
            get {
                return ResourceManager.GetString("_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string _66 {
            get {
                return ResourceManager.GetString("_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string _67 {
            get {
                return ResourceManager.GetString("_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string _68 {
            get {
                return ResourceManager.GetString("_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Affiliation.
        /// </summary>
        public static string _69 {
            get {
                return ResourceManager.GetString("_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Lab Result.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor.
        /// </summary>
        public static string _70 {
            get {
                return ResourceManager.GetString("_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string _71 {
            get {
                return ResourceManager.GetString("_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string _72 {
            get {
                return ResourceManager.GetString("_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant Email.
        /// </summary>
        public static string _73 {
            get {
                return ResourceManager.GetString("_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed.
        /// </summary>
        public static string _74 {
            get {
                return ResourceManager.GetString("_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string _75 {
            get {
                return ResourceManager.GetString("_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string _76 {
            get {
                return ResourceManager.GetString("_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string _77 {
            get {
                return ResourceManager.GetString("_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Classification:.
        /// </summary>
        public static string _78 {
            get {
                return ResourceManager.GetString("_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspected Disease.
        /// </summary>
        public static string _79 {
            get {
                return ResourceManager.GetString("_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial ICD10 Name:.
        /// </summary>
        public static string _80 {
            get {
                return ResourceManager.GetString("_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Category:   .
        /// </summary>
        public static string _81 {
            get {
                return ResourceManager.GetString("_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Entered By:.
        /// </summary>
        public static string _82 {
            get {
                return ResourceManager.GetString("_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDPeTT User Guide.
        /// </summary>
        public static string _83 {
            get {
                return ResourceManager.GetString("_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the merge.
        /// </summary>
        public static string _84 {
            get {
                return ResourceManager.GetString("_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident.
        /// </summary>
        public static string _85 {
            get {
                return ResourceManager.GetString("_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort.
        /// </summary>
        public static string _86 {
            get {
                return ResourceManager.GetString("_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous import date.
        /// </summary>
        public static string _87 {
            get {
                return ResourceManager.GetString("_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string _88 {
            get {
                return ResourceManager.GetString("_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string _89 {
            get {
                return ResourceManager.GetString("_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Facility.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of the last import.
        /// </summary>
        public static string _90 {
            get {
                return ResourceManager.GetString("_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files packaged:.
        /// </summary>
        public static string _91 {
            get {
                return ResourceManager.GetString("_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Import.
        /// </summary>
        public static string _92 {
            get {
                return ResourceManager.GetString("_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Open import folder.
        /// </summary>
        public static string _93 {
            get {
                return ResourceManager.GetString("_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import status.
        /// </summary>
        public static string _94 {
            get {
                return ResourceManager.GetString("_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string _95 {
            get {
                return ResourceManager.GetString("_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohort Number.
        /// </summary>
        public static string _96 {
            get {
                return ResourceManager.GetString("_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University/Training Institution.
        /// </summary>
        public static string _97 {
            get {
                return ResourceManager.GetString("_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Status.
        /// </summary>
        public static string _98 {
            get {
                return ResourceManager.GetString("_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FETP Track.
        /// </summary>
        public static string _99 {
            get {
                return ResourceManager.GetString("_99", resourceCulture);
            }
        }
    }
}
